codio/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^view/single/$', RedirectView.as_view(url='/view/single/1')),
    url(r'^view/single/(?P<code_id>\w+)/$', views.code_single, name='code_single'),

    url(r'^view/search/$', views.search, name='search'),
    url(r'^view/search/tag/(?P<tag>\w+)/$', views.search_tag, name='search_tag'),
    url(r'^view/search/lang/(?P<lang>\w+)/$', views.search_lang, name='search_lang'),
    url(r'^view/search/dev/(?P<dev>\w+)/$', views.search_dev, name='search_dev'),

    url(r'^view/$', RedirectView.as_view(url='/view/list')),
    url(r'^view/list/$', views.code_list, name='code_list'),

    url(r'^edit/code/(?P<code_id>\w+)/$', views.edit_code, name='edit_code'),
    url(r'^remove/code/(?P<code_id>\w+)/$', views.remove_code, name='remove_code'),

    url(r'^user/profile/$', views.user_profile, name='user_profile'),
    url(r'^user/submissions/$', views.user_codes, name='user_codes'),

    url(r'^user/(?P<user_id>\w+)/profile/$', views.user_profile, name='user_profile'),
    url(r'^user/(?P<user_id>\w+)/submissions/$', views.user_codes, name='user_codes'),

    url(r'^submit-code/$', views.submit_code, name='submit_code'),
]

djangowww/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('codio.urls'))
]

codio/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
# Create your models here.
class code(models.Model):
    title  = models.CharField(max_length=200)
    developer = models.ForeignKey("auth.User")
    add_date = models.DateTimeField(default=timezone.now)
    language = models.CharField(max_length=20)
    usage = models.TextField()
    code_text = models.TextField()   #the code
    input_output = models.TextField(null=True,blank=True)   #combined
    level_choices = (
        (0,"Beginner"),
        (1,"Intermediate"),
        (2,"Advanced"),
    )
    level = models.IntegerField(choices=level_choices,null=False,default=0)
    tags = models.TextField(null=True,blank=True)   #comma separated tags

    def __str__(self):
        return self.title

class notification(models.Model):
    text = models.TextField()
    user = models.ForeignKey("auth.User")
    add_date = models.DateTimeField(default=timezone.now)
    read = models.BooleanField(default=False)

codio/forms.py
from django import forms
from .models import code

class submit_form(forms.ModelForm):
    class Meta:
        model = code
        fields = ('title','usage','code_text','input_output','tags')

codio/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import code
from django.db.models import Q
from .forms import submit_form
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
import string
# Create your views here.

def code_list(request):
    code_list = code.objects.all().order_by('-add_date')
    content = {
    'code_list':code_list,
    'page_title':'Codes',
    }
    return render(request, 'code-list.html', content)

def code_single(request,code_id):
    code_single = code.objects.get(id=int(code_id))
    tags = code_single.tags.split(",")
    return render(request, 'code-single.html',{'code':code_single, 'tags':tags, })


def home(request):
    return render(request,'index.html')




def search_tag(request,tag):
    code_list = code.objects.filter(tags__contains=tag).order_by('add_date')
    content = {
    'code_list':code_list,
    'page_title':'Search - Tag',
    }
    return render(request, 'code-list.html', content)

def search_lang(request,lang):
    code_list = code.objects.filter(language=lang).order_by('add_date')
    content = {
    'code_list':code_list,
    'page_title':'Search - Language',
    }
    return render(request, 'code-list.html', content)

def search_dev(request,dev):
    code_list = code.objects.filter(developer=dev).order_by('add_date')
    content = {
    'code_list':code_list,
    'page_title':'Search - Developer',
    }
    return render(request, 'code-list.html', content)

def search(request):
    if request.method == 'POST':
        results = code.objects.all()
        searches = request.POST.get('q', "")
        for search in searches.split(" "):
            if search:
                results = results.filter(title__contains=search) | results.filter(language__contains=search) | \
                results.filter(tags__contains=search) | results.filter(usage__contains=search) | results.filter(code_text__contains=search)
            content = {
            'code_list':results,
            'page_title':'Search',
            }
        return render(request, 'code-list.html', content)
    else:
        return HttpResponseRedirect('/view/list')


def user_profile(request,user_id=0):
    if user_id==0:
        if request.user.is_authenticated:
            user_id = request.user.id
        else:
            return HttpResponseRedirect('/view/list/')

    code_list = code.objects.filter(developer=user_id)
    no_codes = code_list.count()
    return render(request,'user-profile.html',{'no_codes':no_codes,})

def user_codes(request,user_id=0):
    if user_id==0:
        if request.user.is_authenticated:
            user_id = request.user.id
        else:
            return HttpResponseRedirect('/view/list/')
    code_list = code.objects.filter(developer=user_id)
    content = {
        'code_list':code_list,
        'page_title': str(User.objects.get(pk=user_id)) + ' - Submissions',
        }
    return render(request,'code-list.html',content)





def edit_code(request,code_id):
    ecode = code.objects.get(id=code_id)
    if request.method == 'POST':
        ecode.title = request.POST.get("title",ecode.title)
        ecode.usage = request.POST.get("usage", ecode.usage)
        ecode.code_text = request.POST.get("code_text", ecode.code_text)
        ecode.input_output = request.POST.get("input_output", ecode.input_output)
        ecode.tags = request.POST.get("tags", ecode.tags)
        ecode.level = request.POST.get("level",ecode.level)
        ecode.save()
    return HttpResponseRedirect('/view/single/' + str(code_id))

def remove_code(request,code_id):
    ecode = code.objects.get(id=code_id).delete()
    return HttpResponseRedirect('/view/list/')

def submit_code(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = submit_form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            code = form.save(commit=False)
            code.language = request.POST.get("language")
            code.developer = request.user
            code.add_date = timezone.now()
            code.level = request.POST.get("level")
            code.save()
            code_id = code.id
            return HttpResponseRedirect('/view/single/' + str(code_id))
    # if a GET (or any other method) we'll create a blank form
    else:
        if request.user.is_authenticated():
            form = submit_form()
            return render(request, 'submit-code.html', {'form': form})
        else:
            return HttpResponseRedirect('/admin/login/?next=/submit-code/')

codio/templates/code-list.html
<!DOCTYPE html>
  <html>
  {% load static %}
    <head>
      <title>Codio</title>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}"  media="screen,projection"/>
      <!--Let browser know website is optimized for mobile-->
	<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

<body>

{% include 'nav.html' %}

<!--Content starts from here -->
<div style="height:100px; overflow:hidden;" class=""></div>
<div class="container">
    <div class="row">
        <center><h3>{{page_title}}</h3></center><br>

      {% if code_list %}
      <div class="collection z-depth-4">
        {% for code in code_list %}
        <a href="/view/single/{{code.id}}/?back_link={{request.get_full_path}}" class="collection-item waves-effect waves-dark" style="color:black;">
            <h5>{{code.title}} <span class="indigo new badge">{{code.get_level_display}}</span></h5>
            <style>span.badge.new:after{content: ''!important;}</style>
            <div style="color:gray;"><b>Developer :</b><i>
              {% if code.developer.get_full_name %}
                {{code.developer.get_full_name}}
              {% else %}{{code.developer}}{% endif %}</i>
               , <b>Language :</b><i> {{code.language}} </i>
               , <b>Date :</b><i> {{code.add_date}} </i>
             </div>
            <p class="flow-text" style="font-size:1.2em;">{{code.usage | striptags | truncatechars:200}}</p>
        </a>
        {% endfor %}
      </div>
      {% endif %}


{% include 'float-button.html' %}


  </div><!--row end -->
</div><!--container end -->

<div style="height:200px;"></div>




<!--Content end here -->

{% include 'footer.html' %}

<!--Do Not Change from here on -->
      <!--Import jQuery before materialize.js-->

      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>



        <!--This should be after loading jquery only -->
        <script>
            $( document ).ready(function() {
                $(".button-collapse").sideNav();
                $('.tooltipped').tooltip({delay: 50});
                $('.collapsible').collapsible();
                $('.parallax').parallax();
            });
        </script>
  </body>
</html>

codio/templates/code-single.html
<!DOCTYPE html>
  <html>
  {% load static %}
    <head>
      <title>Codio</title>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}"  media="screen,projection"/>
      <!--Let browser know website is optimized for mobile-->

      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <!-- Highlighter-->
      <link rel='stylesheet' href="{% static 'css/highlight/hybrid.css' %}">
      <script src="{% static 'js/highlight.pack.js' %}"></script>
      <script>hljs.initHighlightingOnLoad();</script>
      <!-- Highlighter end-->
	<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    </head>

<body>

{% include 'nav.html' %}

<!--Content starts from here -->
<div style="height:100px; overflow:hidden;" class=""></div>
<div class="container">
    <div class="row">
        {% if request.GET.back_link %}
        <a href="{{request.GET.back_link}}" class="indigo waves-effect waves-light btn"><i class="material-icons large">keyboard_arrow_left</i></a><br><br>
        {% endif %}
<style>
span.badge.new:after{content: ''!important; }span.badge{cursor: pointer;font-size:1.2em;padding:5px;}
#usage,#code_text,#input_output{height:200px;}
</style>

{% if not code.developer.id == request.user.id %}
  <style>.badge{display: none;}</style>
{% endif %}

    {%if code %}
    <ul class="collection with-header z-depth-4">
            <li class="collection-header">
              <h4>{{ code.title }}
                <span class="red darken-4 new badge" style="padding:0px;" onclick="removeform('{{code.id}}')"> &nbsp;&nbsp;Remove&nbsp;&nbsp; </span>
                <span class="indigo new badge" style="padding:0px;" onclick="editform('title','{{code.title}}')">Edit</span>
              </h4>
            </li>
            <li class="collection-item">
              <b>Developer :</b><a href="/view/search/dev/{{ code.developer.id }}">
              {% if code.developer.get_full_name %}
                {{code.developer.get_full_name}}
              {% else %}
                {{code.developer}}
              {% endif %}</a></li>
              <textarea id="code" style="width:2px;height:2px; top:-100px; left:-100px; position:fixed;" >{{code.code_text}}</textarea>
              <div id="inout" style="display:none;">{{code.input_output}}</div>
              <div id="use" style="display:none;">{{code.usage}}</div>
              <li class="collection-item"><b>Language :</b> <a href="/view/search/lang/{{ code.language }}">{{ code.language }}</a></li>
              <li class="collection-item"><b>Date :</b> {{ code.add_date }} </li>
              <li class="collection-item"><b>Usage :</b>
                <span class="indigo new badge" onclick="editform('usage',$('#use').html())">Edit</span>
                {{ code.usage | safe}}
              </li>
              <li class="collection-item"><b>Level :</b>
                <span class="indigo new badge" style="padding:3px;" onclick="editform('level','0')">Edit</span>
                {{ code.get_level_display }}
              </li>
              <li class="collection-item"><b>Code : </b>
                <span id="copybtn" onclick="Materialize.toast('Code Copied!', 4000)" class="green new badge large" data-clipboard-target="#code">Copy</span>
                <span class="indigo new badge"  onclick="editform('code_text',$('#code').html())">Edit</span>
                <pre><code> {{ code.code_text }}</code></pre>
              </li>
              <li class="collection-item"><b>Input and Output :</b> <span class="indigo new badge" onclick="editform('input_output',$('#inout').html())">Edit</span> <pre>{{ code.input_output }}</pre></li>
              <li class="collection-item"><b>Tags :</b><span class="indigo new badge" onclick="editform('tags','{{code.tags}}')">Edit</span>
                {% if tags %}
                {% for tag in tags %}
                  <div class="chip"><a href="/view/search/tag/{{tag}}"> {{ tag }}</a></div>
                  {% endfor %}
                {% endif %}

              </li>
              <li class="collection-item">
                <div class="fb-like" data-href="{{ request.build_absolute_uri}}" data-layout="button_count" data-action="like" data-size="large" data-show-faces="false" data-share="false"></div>

              </li>
              <li class="collection-item">
                <div class="fb-comments"></div>
              </li>
          </ul>

    {% endif %}

  </div><!--row end -->
</div><!--container end -->





<!-- Modal Structure -->
<div id="modal1" class="modal">
  <form method="post" action="/edit/code/{{code.id}}/" id="forms">
    {% csrf_token %}

  <div class="modal-content" id="model-content">

  </div>
  <div class="modal-footer">
    <a class="btn-large waves-effect waves-light indigo modal-action modal-close" onclick="formsubmit();" href="#">Change</a>
  </div>
  </form>
</div>

<script type="text/javascript">
    function editform(field,val){
      $('#model-content').html("");
      $('#model-content').append('<h4>Edit </h4><label>'+ field +' : </label>');

      if (field=='title'){
        $('#model-content').append('<input type="text" value="'+val+'" placeholder="Enter Value" id="'+ field +'" name="'+ field +'" >');
      }
      else if (field=='level') {
        $('#model-content').append('<select name="'+ field +'" style="display:block;">\
              <option value="0">Beginner</option>\
              <option value="1">Intermediate</option>\
              <option value="2">Advanced</option>\
            </select>');
      }
      else { $('#model-content').append('<textarea id="'+ field +'" name="'+ field +'" >'+val+'</textarea>'); }

      $('#modal1').modal('open');
    }

    function formsubmit(){
      $.post( "/edit/code/{{code.id}}/", $( "#forms" ).serialize() );
      window.location.reload(false);
    }

    function removeform(code_id){
      var result = confirm("Are you sure you want to delete \"{{code.title}}\"?");
      if (result) {
          window.location.href = "/remove/code/" + code_id;
      }

    }




</script>




<div style="height:200px;"></div>


<!--Content end here -->

{% include 'float-button.html' %}

{% include 'footer.html' %}

<!--Do Not Change from here on -->
      <!--Import jQuery before materialize.js-->

      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
      <script src="{% static 'js/clipboard.min.js' %}"></script>


        <!--This should be after loading jquery only -->
        <script>
            $( document ).ready(function() {
                $(".button-collapse").sideNav();
                $('.tooltipped').tooltip({delay: 50});
                $('.collapsible').collapsible();
                $('.parallax').parallax();
                $('.modal').modal();
                $('select').material_select();


                //var clipboard = new Clipboard('#copybtn');

            });

        </script>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>




  </body>
</html>

codio/templates/float-button.html
<div class="fixed-action-btn toolbar" style=" right:12%;" id="floatbtn">
  <a class="btn-floating btn-large indigo " >
    <i class="large material-icons" onclick="$('#q').select();">search</i>
  </a>
  <ul>
    <li class="waves-effect waves-light row">
    <form method="post" action="/view/search/">{% csrf_token %}
      <div class="input-field col s6" style="float:none; margin:10px auto;">
          <input type="text" class="validate" id="q" name="q" placeholder="Search">
          <style>::-webkit-input-placeholder { /* Chrome */
            color: white;
          }</style>
        </div>
    </form>
    </li>

  </ul>
</div>

codio/templates/footer.html
<!--Footer Start -->
<footer class="page-footer indigo darken-2">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12" style="display:none;">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright indigo darken-4">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
<!--Footer End -->

codio/templates/index.html
<!DOCTYPE html>
  <html>
  {% load static %}
    <head>
      <title>Codio</title>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}"  media="screen,projection"/>
      <!--Let browser know website is optimized for mobile-->
      <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

<body>


{% include 'nav.html' %}

<!--Content starts from here -->
<div style="height:100px; overflow:hidden;" class=""></div>
<div class="container">
    <div class="row">
        <h2>What is Codio?</h2>
        <div class="flow-text">Codio is an online coding platform which allows developers to share their awesome code with other developers.
            We help people write better, more optimised code faster.
        </div>

        <br>
        <h4>Who made this?</h4>
        <div class="flow-text">This online service has been created by college students. This was a hobby project, we want to help developers
            find good code faster.
        </div>

        <br>
        <h4>How do I get started?</h4>
        <div class="flow-text">You can follow the following steps to start quickly :
            <ol>
                <li>Create a new Account.</li>
                <li>Go to the <a href="#">Submit Code</a> page.</li>
                <li>Fill all the required fields for Title, Language, code etc.</li>
                <li>Submit the code and share the link with your friends.</li>
            </ol>
            You can also go to the view code page to view code submitted by other developers, you can search,filter and sort the code easily.
        </div>
        <br><br><br>


    </div><!--Row End -->

</div><!--Container End -->

<div class="parallax-container ">

            <div class="parallax"><img src="{% static 'img/codeback.png' %}">
                <div class="valign-wrapper" style="height:100%">
                    <div class="card valign" style="float:none; margin:0 auto; opacity:0.9;" >
                                <div class="card-content">
                                  <p>So Ready to get started Submit your code or View code submitted by others!</p>
                                </div>
                                <div class="card-action"><center>
                                        <a class="blue waves-effect waves-light btn btn-large" style="opacity:1;" href="#">Submit Code</a>
                                        <a class="blue waves-effect waves-light btn btn-large" style="opacity:1;" href="#">View Code</a>
                                        </center>
                                </div>
                    </div>
                </div><!--valign-wrapper-->
            </div>
</div><!--Parallax end-->


<div style="height:200px;"></div>




<!--Content end here -->

{% include 'footer.html' %}

<!--Do Not Change from here on -->
      <!--Import jQuery before materialize.js-->

      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>



        <!--This should be after loading jquery only -->
        <script>
            $( document ).ready(function() {
                $(".button-collapse").sideNav();
                $('.tooltipped').tooltip({delay: 50});
                $('.collapsible').collapsible();
                $('.parallax').parallax();
            });
        </script>

</body>
</html>

codio/templates/nav.html
<!--Navbar Fixed Start -->
<div class="navbar-fixed hide-on-med-and-down" >

<!--Topbar Start -->
    <nav class="indigo darken-4 " role="navigation" style="height:25px;" id="nav1">
        <div class="nav-wrapper container" style="line-height:25px; font-size:0.9em;">
           <div style="float:left;">Lets code better!</div>
            <div style="float:right;" class="hide-on-med-and-down">This is a very long text which should not appear on moblie site.</div>
        </div>
    </nav>
<!--Topbar end -->

<!--Navigation Start -->

    <nav class="indigo darken-2" role="navigation" style="top:25px;" id="nav2">
        <div class="nav-wrapper container">
          <a id="logo-container" href="/" class="brand-logo">Codio</a>

          <ul class="right ">
            <li><a href="/" class="tooltipped" data-tooltip="Home"><i class="material-icons">home</i></a></li>
         <li><a href="/submit-code" class="tooltipped" data-tooltip="Submit Code"><i class="material-icons">add</i></a></li><!--Submit Code -->
         <li><a href="/view/list" class="tooltipped" data-tooltip="View Code"><i class="material-icons">code</i></a></li><!--View Code -->
         {% if request.user.is_authenticated %}
          <li><a class="dropdown-button tooltipped" href="#!" data-activates="loggedinuser" data-tooltip="You are Logged in">
              {{request.user}}<i class="material-icons right">arrow_drop_down</i></a>
          </li>
        {% else %}
          <li><a href="/admin/login/?next={{request.get_full_path}}" class="tooltipped" data-tooltip="Login to Codio">Login</a></li>
        {% endif %}
          </ul>
        </div>
    </nav>
<!--Navigation End -->


<!-- Logged In user Info start-->
<ul id="loggedinuser" class="dropdown-content" style="min-width:200px; z-index:2;">
  <li><a href="/user/profile/">Profile</a></li>
  <li><a href="/user/submissions/">Submissions</a></li>
  <li class="divider"></li>
  <li><a href="/admin/logout/?next={{request.get_full_path}}">Logout</a></li>
</ul>
<!--Logged in User info end -->

</div><!--Navbar Fixed End -->

<!--Mobile Navigation Start -->
<nav class="indigo darken-3 hide-on-large-only">
    <div class="nav-wrapper ">
          <a id="logo-container" href="#" class="brand-logo">Codio</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="side-nav" id="mobile-demo" style="z-index:999;">
            <li><a href="/"><i class="material-icons">home</i> Home</a></li>
            <li><a href="/submit-code"><i class="material-icons">add</i> Submit Code</a></li>
            <li><a href="/view/list/"><i class="material-icons">code</i> View Code</a></li>
            <li class="divider"></li>
            {% if request.user.is_authenticated %}
            <li><a href="/user/profile/">Profile</a></li>
            <li><a href="/user/submissions/">Submissions</a></li>
            <li><a href="/admin/logout/?next={{request.get_full_path}}">Logout</a></li>
            {% else %}
            <li><a href="/admin/login/?next={{request.get_full_path}}">Login</a></li>
            {% endif %}
          </ul>
    </div>
</nav>
<!--Mobile Navigation End -->


<script type="text/javascript">
if(window.jQuery){
  $(window).scroll(function() {
     if($(document).scrollTop() > 1) {
         console.log("Not on top");
         document.getElementById("nav1").style.display="none";
         document.getElementById("nav2").style.top="-6px";
         document.getElementById("nav2").style.height="58px";
         //document.getElementById("floatbtn").style.top = "55px";
     }
     else {
       document.getElementById("nav1").style.display="block";
       document.getElementById("nav2").style.top="25px";
       document.getElementById("nav2").style.height="64px";
       //document.getElementById("floatbtn").style.top = "91px";
     }
  });

}
</script>

codio/templates/submit-code.html
<!DOCTYPE html>
  <html>
  {% load static %}
    <head>
      <title>Codio</title>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}"  media="screen,projection"/>
      <!--Let browser know website is optimized for mobile-->
      <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

<body>

{% include 'nav.html' %}

<!--Content starts from here -->
<div style="height:100px; overflow:hidden;" class=""></div>
<div class="container">
    <div class="row">
      <center><h3>Submit Code</h3></center>
      {% if request.user.is_authenticated %}
<div class="col s12 m10 l12 card z-depth-4" style="float:none; margin:0 auto; padding:40px;">

      <form class="" action="/submit-code/" method="post">
        {% csrf_token %}
          {{ form }}<br><br>
          <label for="language">Language: </label>
          <select name="language" style="display:block;">
            <option value="PYTHON" class="selected">Python</option>
            <option value="JAVA">Java</option>
            <option value="C">C</option>
            <option value="CPP">C++</option>
            <option value="ARDUINO">Arduino</option>
            <option value="PHP">PHP</option>
            <option value="Ruby">Ruby</option>
            <option value="VISUAL-BASIC">Visual Basic</option>
            <option value="C-SHARP">C#</option>
            <option value="JAVASCRIPT">Javascript</option>
            <option value="XML">XML</option>
            <option value="HTML">HTML</option>
            <option value="CSS">CSS</option>
          </select>
          <label for="level">Level: </label>
              <select name="level" style="display:block;">
                <option value="0" class="selected">Beginner</option>
                <option value="1">Intermediate</option>
                <option value="2">Advanced</option>
              </select>
              <br><br>
          <input class="indigo waves-effect waves-light btn-large" type="submit" value="Submit Code">
          <input class="indigo waves-effect waves-light btn-large" type="reset" value="Reset">
      </form>

</div>
{% else %}
<center><br><br><br><br>
<a href="/admin/login/?next={{request.get_full_path}}" class="tooltipped waves-effect indigo btn-large waves-light" data-tooltip="Login to Codio">Login</a>
</center>
{% endif %}

<style>
#id_usage{height: 200px;}
#id_code_text{height: 350px;}
#id_input_output{height: 200px;}
label{color: #333; line-height: 40px;}
</style>

  </div><!--row end -->
</div><!--container end -->

{% include 'float-button.html' %}

<div style="height:200px;"></div>

<!--Content end here -->

{% include 'footer.html' %}

<!--Do Not Change from here on -->
      <!--Import jQuery before materialize.js-->

      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>



        <!--This should be after loading jquery only -->
        <script>
            $( document ).ready(function() {
                $(".button-collapse").sideNav();
                $('.tooltipped').tooltip({delay: 50});
                $('.collapsible').collapsible();
                $('.parallax').parallax();
            });
        </script>
  </body>
</html>